### ISSUE TITLE
use Doctrine\Common\Persistence to use Doctrine\Persistence

### ISSUE THREAD

**Issue by HerveDelvaux** [LM-Commons/LmcRbacMvc#16]
In **ObjectRepositoryRoleProvider** : 
`use Doctrine\Common\Persistence\ObjectRepository;` is wrong.
It should be 
`use Doctrine\Persistence\ObjectRepository;`

ObjectRepository.php has been moved
https://github.com/doctrine/persistence/blob/2.1.x/lib/Doctrine/Persistence/ObjectRepository.php

Same in **ObjectRepositoryRoleProviderFactory** : 
```
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\Persistence\ObjectRepository;

```
Replace by : 
```
use Doctrine\Persistence\ObjectManager;
use Doctrine\Persistence\ObjectRepository;
```

**Comment by visto9259** [comment]
Will look into it.  Thanks.

**Comment by visto9259** [comment]
@HerveDelvaux This is code that was there when we migrated to Laminas.  

It is not wrong if you are using doctrine/persistence v1.x.  The issue is that there are references to doctrine in the code but the dependencies on doctrine are not set in composer.json.  This is not good practice as it won't work if you require doctrine/persistence v2 and if the dependency on persistence v1 is set in composer then it will cause redolution issues for those using persistence v2.

I am thinking that **ObjectRepositoryRoleProvider** and its factory should be moved out entirely from LmcRbacMvc and put into its own library such as LmcRbacMvcORM with v1 and v2 branches for persistence.

Any thoughts?

**Comment by svycka** [comment]
@visto9259 I think we long time ago decided to split lmcRbacMvc into alt least two parts one for rbac that would be LmcRbac and this module would then be refactored to use it for laminas-mvc. I am not sure we should support this version if we plan to rewrite it no? This was decided to better support the middleware thing. And LmcRbac already is ready for production use at least I am using it.

**Comment by visto9259** [comment]
LmcRbacMvc has more than 20K downloads between the lm-commons and laminas-commons versions.  LmcRbac around 3K downloads.  No intentions to abandon LmcRbacMVc. 
LmcRbac is better suited for middleware, I guess.  I don't know since I don't use it.  I do use LmcRbacMvc and so do a lot of other apps.

**Comment by JoshBour** [comment]
Hey, any plans on this issue? I tried updating recently and stumbled across this, so for now I explicitely require v1.x of doctrine/persistence but I would like to move on to v2.

**Comment by visto9259** [comment]
@JoshBour I will address this over the weekend.  

My plan is:
- Create a 3.2.x version for `doctrine/persistence v2` 
- Keep the 3.1.x version for `doctrine/persistence v1`

Ultimately, I would like to move doctrine out of this module and let it have its own repo.  Beyond that, I would like to have `LmcRbac` and `LmcRbacMvc` to be part of the same RBAC framework (but not one bundle).  That's going to need some thinking.

**Comment by visto9259** [comment]
Version 3.2.0 uses persistence v2
version 3.1.3 uses persistence v1
