### ISSUE TITLE
AssertionInterface does not describe the context

### ISSUE THREAD

**Issue by egoncommerce** [LM-Commons/LmcRbacMvc#20]
At this very moment I cannot implememt the AssertionInterface with context, it is not described in this interface. 
I tried to override the AssertionInterface with my own, thus with the **$context = null** parameter. But... the AssertionPluginManager is not that flexible: "Assertions must implement "LmcRbacMvc\Assertion\AssertionInterface", but "Application\Assertion\MustBeWebsiteOwner" (MustBeWebsiteOwner implements my AssertionInterface, with $context...)

So... should the AssertionInterface not be like this?
```
interface AssertionInterface
{
    /**
     * Check if this assertion is true
     *
     * @param  AuthorizationService $authorizationService
     * @param  mixed                $context
     * @return bool
     */
    public function assert(AuthorizationService $authorizationService, $context = null);
}
```
Edit: I used a quick and dirty workaround like this to get my context:

`$context = \func_get_arg(1);`

**Comment by visto9259** [comment]
Hi @egoncommerce,

Although I am the maintainer, I did not write the orignal code and this is part of the code that I am not familiar with.

Looking at the `AssertionInterface` definition, it does not match the PHPDoc parameters for function `assert`.  Not sure what was the original intent here but this looks like a bug to me and I will investigate and correct as needed.

In the meantime, instead of creating your own version of `AssertionInterface`, I would create a version that extends `AssertionInterface` like this:

```php
interface MyAssertionInterface extends AssertionInterface
{
    public function assert(AuthorizationService $authorizationService, $context=null);
}
```
This will pass the validation done by the plugin manager for the `instanceOf AssertionInterface`.

Hope this helps for the time being as it will take me a while to update the code and release it.

**Comment by egoncommerce** [comment]
@visto9259 Thanks for your quick reply, I replaced my quick and dirty workaround with your suggestion and I'd like to say: It Works! _o_
